# Generated by Django 3.2 on 2022-01-01 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('immasin', '0004_slide2_slide3'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slide3',
            name='author',
        ),
        migrations.DeleteModel(
            name='Slide2',
        ),
        migrations.DeleteModel(
            name='Slide3',
        ),
    ]
