# Generated by Django 3.2 on 2022-01-04 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('immasin', '0007_slide1_strength'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='strength',
        ),
        migrations.RemoveField(
            model_name='post',
            name='strength',
        ),
        migrations.DeleteModel(
            name='Slide1',
        ),
    ]
