# Generated by Django 3.2 on 2022-01-04 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('immasin', '0008_auto_20220104_1436'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='group',
            field=models.CharField(choices=[('mobile', 'mobile'), ('pc', 'pc'), ('notebook', 'notebook'), ('accessories', 'accessories')], default='mobile', max_length=20),
        ),
    ]
