# Generated by Django 3.2 on 2022-01-05 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('immasin', '0011_post_grop'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='grop',
            field=models.CharField(choices=[('notebook', 'notebook'), ('accessories', 'accessories'), ('pc', 'pc'), ('mobile', 'mobile')], default='mobile', max_length=20),
        ),
    ]
