# Generated by Django 3.2 on 2022-01-07 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('immasin', '0012_alter_post_grop'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='grop',
            field=models.CharField(choices=[('mobile', 'mobile'), ('accessories', 'accessories'), ('pc', 'pc'), ('notebook', 'notebook')], default='mobile', max_length=20),
        ),
    ]
