# Generated by Django 3.2 on 2022-01-07 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('immasin', '0013_alter_post_grop'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='grop',
            field=models.CharField(choices=[('slide', 'slide'), ('post', 'post')], default='post', max_length=20),
        ),
    ]
