# Generated by Django 3.2 on 2022-01-07 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('immasin', '0014_alter_post_grop'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='grop',
            field=models.CharField(choices=[('slide2', 'slide2'), ('post', 'post'), ('slide1', 'slide1'), ('slide3', 'slide3')], default='post', max_length=20),
        ),
    ]
