# Generated by Django 3.2 on 2022-01-12 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('immasin', '0015_alter_post_grop'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='grop',
            field=models.CharField(choices=[('slide3', 'slide3'), ('slide1', 'slide1'), ('post', 'post'), ('about', 'about'), ('slide2', 'slide2')], default='post', max_length=20),
        ),
    ]
